name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisez "windows-latest" ou "macos-latest" si nécessaire
    name: Test changed-files

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> Pour récupérer le commit précédent.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Changed files:"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create diff file
        run: |
          git diff > test_diff.txt

      - name: Display contents of test_diff.txt
        run: cat test_diff.txt

      - name: Run Python script for code review
        working-directory: calc
        env: 
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python review.py -f ../test_diff.txt
